spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8://sql_study
    username: gutenlee
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create